// let listProducts=[
//     {
//         id:1,
//         name:"Váy 2 dây denim",
//         price: 549000,
//         img:["./img/vay/vay-2-day-denim-1.webp","./img/vay/vay-2-day-denim-2.webp","./img/vay/vay-2-day-denim-3.webp",
//         "./img/vay/vay-2-day-denim-0.webp"],
//         quantity:50,
//         categoryId:1,
//     },
//     {
//         id:2,
//         name:"Váy gile dáng chữ A",
//         price: 599000,
//         img:["./img/vay-gile-dang-chu-a-1.webp","./img/vay/vay-gile-dang-chu-a-2.webp","./img/vay/vay-gile-dang-chu-a-3.webp",
//         "./img/vay/vay-gile-dang-chu-a-4.webp"],
//         quantity:50,
//         categoryId:1,
//     },
//     {
//         id:3,
//         name:"Váy midi 2 dây",
//         price: 549000,
//         img:["./img/vay/vay-midi-2-day-1.webp","./img/vay/vay-midi-2-day-2.webp","./img/vay/vay-midi-2-day-3.webp",
//         "./img/vay/vay-midi-2-day-4.webp"],
//         quantity:50,
//         categoryId:1
//     },
//     {
//         id:4,
//         name:"Váy midi hoa 2 dây",
//         price: 349500 ,
//         img:["./img/vay/vay-midi-hoa-2-day-1.webp","./img/vay/vay-midi-hoa-2-day-2.webp","./img/vay/vay-midi-hoa-2-day-3.webp",
//         "./img/vay/vay-midi-hoa-2-day-4.webp"],
//         quantity:50,
//         categoryId:1
//     },
//     {
//         id:5,
//         name:"Váy midi hoa tay bồng",
//         price: 799000 ,
//         img:["./img/vay/vay-midi-hoa-tay-bong-1.webp","./img/vay/vay-midi-hoa-tay-bong-2.webp","./img/vay/vay-midi-hoa-tay-bong-3.webp",
//         "./img/vay/vay-midi-hoa-tay-bong-4.webp"],
//         quantity:50,
//         categoryId:1
//     },
//     {
//         id:6,
//         name:"Váy midi hồng cổ phối nơ",
//         price: 799000,
//         img:["./img/vay/vay-midi-hong-co-phoi-no-1.webp","./img/vay/vay-midi-hong-co-phoi-no-2.webp","./img/vay/vay-midi-hong-co-phoi-no-3.webp",
//         "./img/vay/vay-midi-hong-co-phoi-no-4.webp"],
//         quantity:50,
//         categoryId:1
//     },
//     {
//         id:7,
//         name:"Váy midi tay rủ",
//         price: 699000,
//         img:["./img/vay/vay-midi-tay-ru-1.webp","./img/vay/vay-midi-tay-ru-2.webp","./img/vay/vay-midi-tay-ru-3.webp",
//         "./img/vay/vay-midi-tay-ru-4.webp"],
//         quantity:50,
//         categoryId:1
//     },
//     {
//         id:8,
//         name:"Váy mini trễ vai",
//         price: 349500 ,
//         img:["./img/vay/vay-midi-tre-vai-1.webp","./img/vay/vay-midi-tre-vai-2.webp","./img/vay/vay-midi-tre-vai-3.webp",
//         "./img/vay/vay-midi-tre-vai-3.webp"],
//         quantity:50,
//         categoryId:1
//     },
//     {
//         id:9,
//         name:"Váy 2 dây denim",
//         price: 549000,
//         img:["./img/vay/vay-2-day-denim-1.webp","./img/vay/vay-2-day-denim-2.webp","./img/vay/vay-2-day-denim-3.webp",
//         "./img/vay/vay-2-day-denim-0.webp"],
//         quantity:50,
//         categoryId:1
//     },
//     {
//         id:10,
//         name:"Váy mini cổ phối đăng ten",
//         price: 599000,
//         img:["./img/vay/vay-mini-co-phoi-dang-ten-1.webp","./img/vay/vay-mini-co-phoi-dang-ten-2.webp","./img/vay/vay-mini-co-phoi-dang-ten-3.webp",
//         "./img/vay/vay-mini-co-phoi-dang-ten-1.webp"],
//         quantity:50,
//         categoryId:1
//     },
//     {
//         id:11,
//         name:"Áo ren tay bồng",
//         price: 599000,
//         img:["./img/ao/ao-ren-tay-bong-1.webp","./img/ao/ao-ren-tay-bong-2.webp","./img/ao/ao-ren-tay-bong-3.webp",
//         "./img/ao/ao-ren-tay-bong-4.webp"],
//         quantity:50,
//         categoryId:2,
//     },
//     {
//         id:12,
//         name:"Áo sơ mi denim dáng rộng",
//         price: 449000,
//         img:["./img/ao/ao-so-mi-denim-dang-rong-1.webp","./img/ao/ao-so-mi-denim-dang-rong-2.webp","./img/ao/ao-so-mi-denim-dang-rong-3.webp",
//         "./img/ao/ao-so-mi-denim-dang-rong-4.webp"],
//         quantity:50,
//         categoryId:2,
//     }, 
//     {
//         id:13,
//         name:"Áo sơ mi kẻ dáng suông",
//         price: 599000,
//         img:["./img/ao/ao-so-mi-ke-dang-suong-1.webp","./img/ao/ao-so-mi-ke-dang-suong-2.webp","./img/ao/ao-so-mi-ke-dang-suong-3.webp",
//         "./img/ao/ao-so-mi-ke-dang-suong-4.webp"],
//         quantity:50,
//         categoryId:2,
//     },
//     {
//         id:14,
//         name:"Áo sơ mi ren cổ trụ",
//         price: 649000,
//         img:["./img/ao/ao-ren-tay-bong-1.webp","./img/ao/ao-ren-tay-bong-2.webp","./img/ao/ao-ren-tay-bong-3.webp",
//         "./img/ao/ao-ren-tay-bong-4.webp"],
//         quantity:50,
//         categoryId:2,
//     },
//     {
//         id:15,
//         name:"Áo sơ mi tay bồng",
//         price: 549000,
//         img:["./img/ao/ao-so-mi-tay-bong-1.webp","./img/ao/ao-so-mi-tay-bong-2.webp","./img/ao/ao-so-mi-tay-bong-3.webp",
//         "./img/ao/ao-so-mi-tay-bong-4.webp"],
//         quantity:50,
//         categoryId:2,
//     },
//     {
//         id:16,
//         name:"Áo thiết kế dáng suông",
//         price: 499000,
//         img:["./img/ao/ao-thiet-ke-dang-suong-1.webp","./img/ao/ao-thiet-ke-dang-suong-2.webp","./img/ao/ao-thiet-ke-dang-suong-3.webp",
//         "./img/ao/ao-thiet-ke-dang-suong-4.webp"],
//         quantity:50,
//         categoryId:2,
//     },
//     {
//         id:17,
//         name:"Áo trễ vai",
//         price: 449000,
//         img:["./img/ao/ao-tre-vai-1.webp","./img/ao/ao-tre-vai-2.webp","./img/ao/ao-tre-vai-3.webp",
//         "./img/ao/ao-tre-vai-4.webp"],
//         quantity:50,
//         categoryId:2,
//     },
//     {
//         id:18,
//         name:"Áo vest ngắn tay",
//         price: 649000,
//         img:["./img/ao/ao-vest-ngan-tay-1.webp","./img/ao/ao-vest-ngan-tay-2.webp","./img/ao/ao-vest-ngan-tay-3.webp",
//         "./img/ao/ao-vest-ngan-tay-4.webp"],
//         quantity:50,
//         categoryId:2,
//     },
//     {
//         id:19,
//         name:"Quần dài ống rộng",
//         price: 599000,
//         img:["./img/quan/quan-dai-ong-rong-1.webp","./img/quan/quan-dai-ong-rong-2.webp","./img/quan/quan-dai-ong-rong-3.webp",
//         "./img/quan/quan-dai-ong-rong-4.webp"],
//         quantity:50,
//         categoryId:3,
//     },
//     {
//         id:20,
//         name:"Quần dài ống suông",
//         price: 399000,
//         img:["./img/quan/quan-dai-ong-suong-1.webp","./img/quan/quan-dai-ong-suong-2.webp","./img/quan/quan-dai-ong-suong-3.webp",
//         "./img/quan/quan-dai-ong-suong-4.webp"],
//         quantity:50,
//         categoryId:3,
//     },
//     {
//         id:21,
//         name:"Quần ống suông hoạ tiết",
//         price: 699000,
//         img:["./img/quan/quan-dai-ong-suong-hoa-tiet-1.webp","./img/quan/quan-dai-ong-suong-hoa-tiet-2.webp","./img/quan/quan-dai-ong-suong-hoa-tiet-3.webp",
//         "./img/quan/quan-dai-ong-suong-hoa-tiet-4.webp"],
//         quantity:50,
//         categoryId:3,
//     },
//     {
//         id:22,
//         name:"Quần short cạp cao",
//         price: 449000,
//         img:["./img/quan/quan-short-cap-cao-1.webp","./img/quan/quan-short-cap-cao-2.webp","./img/quan/quan-short-cap-cao-3.webp",
//         "./img/quan/quan-short-cap-cao-4.webp"],
//         quantity:50,
//         categoryId:3,
//     },
//     {
//         id:23,
//         name:"Quần short gập gấu",
//         price: 499000,
//         img:["./img/quan/quan-short-gap-gau-1.webp","./img/quan/quan-short-gap-gau-2.webp","./img/quan/quan-short-gap-gau-3.webp",
//         "./img/quan/quan-short-gap-gau-4.webp"],
//         quantity:50,
//         categoryId:3,
//     },
//     {
//         id:24,
//         name:"Quần short hoa nổi",
//         price: 449000,
//         img:["./img/quan/quan-short-hoa-noi-1.webp","./img/quan/quan-short-hoa-noi-2.webp","./img/quan/quan-short-hoa-noi-3.webp",
//         "./img/quan/quan-short-hoa-noi-4.webp"],
//         quantity:50,
//         categoryId:3,
//     },
//     {
//         id:25,
//         name:"Quần short ống rộng",
//         price: 399000,
//         img:["./img/quan/quan-short-ong-rong-1.webp","./img/quan/quan-short-ong-rong-2.webp","./img/quan/quan-short-ong-rong-3.webp",
//         "./img/quan/quan-short-ong-rong-4.webp"],
//         quantity:50,
//         categoryId:3,
//     },
//     {
//         id:26,
//         name:"Quần short xanh",
//         price: 399000,
//         img:["./img/quan/quan-short-xanh-1.webp","./img/quan/quan-short-xanh-2.webp","./img/quan/quan-short-xanh-3.webp",
//         "./img/quan/quan-short-xanh-4.webp"],
//         quantity:50,
//         categoryId:3,
//     },
//     {
//         id:27,
//         name:"Chân váy midi",
//         price: 499000,
//         img:["./img/chan-vay/chan-vay-midi-1.webp","./img/chan-vay/chan-vay-midi-2.webp","./img/chan-vay/chan-vay-midi-3.webp",
//         "./img/chan-vay/chan-vay-midi-4.webp"],
//         quantity:50,
//         categoryId:4,
//     },
//     {
//         id:28,
//         name:"Chân váy midi hồng",
//         price: 449000,
//         img:["./img/chan-vay/chan-vay-midi-hong-1.webp","./img/chan-vay/chan-vay-midi-hong-2.webp","./img/chan-vay/chan-vay-midi-hong-3.webp",
//         "./img/chan-vay/chan-vay-midi-hong-4.webp"],
//         quantity:50,
//         categoryId:4,
//     },
//     {
//         id:29,
//         name:"Chân váy midi xếp li",
//         price: 599000,
//         img:["./img/chan-vay/chan-vay-midi-xep-li-1.webp","./img/chan-vay/chan-vay-midi-xep-li-2.webp","./img/chan-vay/chan-vay-midi-xep-li-3.webp",
//         "./img/chan-vay/chan-vay-midi-xep-li-4.webp"],
//         quantity:50,
//         categoryId:4,
//     },
//     {
//         id:30,
//         name:"Chân váy midi trơn",
//         price: 549000,
//         img:["./img/chan-vay/chan-vay-midi-tron-1.webp","./img/chan-vay/chan-vay-midi-tron-2.webp","./img/chan-vay/chan-vay-midi-tron-3.webp",
//         "./img/chan-vay/chan-vay-midi-tron-4.webp"],
//         quantity:50,
//         categoryId:4,
//     },
//     {
//         id:31,
//         name:"Chân váy mini gấu tua rua",
//         price: 499000,
//         img:["./img/chan-vay/chan-vay-mini-gau-tua-rua-1.webp","./img/chan-vay/chan-vay-mini-gau-tua-rua-2.webp","./img/chan-vay/chan-vay-mini-gau-tua-rua-3.webp",
//         "./img/chan-vay/chan-vay-mini-gau-tua-rua-4.webp"],
//         quantity:50,
//         categoryId:4,
//     },
//     {
//         id:32,
//         name:"Chân váy mini phối nơ",
//         price: 549000,
//         img:["./img/chan-vay/chan-vay-mini-phoi-no-1.webp","./img/chan-vay/chan-vay-mini-phoi-no-2.webp","./img/chan-vay/chan-vay-mini-phoi-no-3.webp",
//         "./img/chan-vay/chan-vay-mini-phoi-no-4.webp"],
//         quantity:50,
//         categoryId:4,
//     },
//     {
//         id:33,
//         name:"Chân váy mini xẻ gấu",
//         price: 499000,
//         img:["./img/chan-vay/chan-vay-mini-xe-gau-1.webp","./img/chan-vay/chan-vay-mini-xe-gau-2.webp","./img/chan-vay/chan-vay-mini-xe-gau-3.webp",
//         "./img/chan-vay/chan-vay-mini-xe-gau-4.webp"],
//         quantity:50,
//         categoryId:4,
//     },
//     {
//         id:34,
//         name:"Set áo croptop và chân váy mini kẻ",
//         price: 599000,
//         img:["./img/set-bo/set-ao-croptop-va-chan-vay-midi-ke-1.webp","./img/set-bo/set-ao-croptop-va-chan-vay-midi-ke-2.webp","./img/set-bo/set-ao-croptop-va-chan-vay-midi-ke-3.webp",
//         "./img/set-bo/set-ao-croptop-va-chan-vay-midi-ke-4.webp"],
//         quantity:50,
//         categoryId:5,
//     },
//     {
//         id:35,
//         name:"Set áo croptop và chân váy midi ren",
//         price: 699000,
//         img:["./img/set-bo/set-ao-croptop-va-chan-vay-midi-ren-1.webp","./img/set-bo/set-ao-croptop-va-chan-vay-midi-ren-3.webp",
//         "./img/set-bo/set-ao-croptop-va-chan-vay-midi-ren-4.webp"],
//         quantity:50,
//         categoryId:5,
//     },
//     {
//         id:35,
//         name:"Set áo dài kèm chân váy",
//         price: 699000,
//         img:["./img/set-bo/set-ao-dai-kem-chan-vay-1.webp","./img/set-bo/set-ao-dai-kem-chan-vay-2.webp","./img/set-bo/set-ao-dai-kem-chan-vay-3.webp",
//         "./img/set-bo/set-ao-dai-kem-chan-vay-4.webp"],
//         quantity:50,
//         categoryId:5,
//     },
//     {
//         id:36,
//         name:"Set áo tay bèo và chân váy",
//         price: 799000,
//         img:["./img/set-bo/set-ao-tay-beo-va-chan-vay-1.webp","./img/set-bo/set-ao-tay-beo-va-chan-vay-2.webp","./img/set-bo/set-ao-tay-beo-va-chan-vay-3.webp",
//         "./img/set-bo/set-ao-tay-beo-va-chan-vay-4.webp"],
//         quantity:50,
//         categoryId:5,
//     },
//     {
//         id:37,
//         name:"Set croptop tay bồng và chân váy",
//         price: 599000,
//         img:["./img/set-bo/set-croptop-tay-bong-va-chan-vay-1.webp","./img/set-bo/set-croptop-tay-bong-va-chan-vay-2.webp","./img/set-bo/set-croptop-tay-bong-va-chan-vay-3.webp",
//         "./img/set-bo/set-croptop-tay-bong-va-chan-vay-4.webp"],
//         quantity:50,
//         categoryId:5,
//     },
// ]

// localStorage.setItem("listProducts", JSON.stringify(listProducts))

// let category=[
//     {id:1,name:'Váy'},
//     {id:2,name:'Áo'},
//     {id:3,name:'Quần'},
//     {id:4,name:'Chân Váy'},
//     {id:5,name:'Set Bộ'},
// ]
// localStorage.setItem('category',JSON.stringify(category))